DROP TABLE IF EXISTS ItemCategory;
DROP TABLE IF EXISTS BidderLocation;
DROP TABLE IF EXISTS Bids;
DROP TABLE IF EXISTS ItemLocation;
DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Seller;
DROP TABLE IF EXISTS Bidder;